"""Canonical operational event taxonomy for the F6 journal envelope."""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    """Closed event names accepted by the canonical execution journal."""

    EXECUTION_CREATED = "EXECUTION_CREATED"
    WORKSPACE_CREATED = "WORKSPACE_CREATED"
    CONTEXT_ASSEMBLED = "CONTEXT_ASSEMBLED"
    CONTEXT_BLOCKED = "CONTEXT_BLOCKED"
    CONTEXT_EVALUATED = "CONTEXT_EVALUATED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_GENERATION_STARTED = "PLAN_GENERATION_STARTED"
    PLAN_GENERATED = "PLAN_GENERATED"
    NODE_STARTED = "NODE_STARTED"
    NODE_COMPLETED = "NODE_COMPLETED"
    NODE_FAILED = "NODE_FAILED"
    MODEL_REQUEST_COMPLETED = "MODEL_REQUEST_COMPLETED"
    MODEL_REQUEST_FAILED = "MODEL_REQUEST_FAILED"
    TOOL_AUTHORIZED = "TOOL_AUTHORIZED"
    TOOL_DENIED = "TOOL_DENIED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    GATE_STARTED = "GATE_STARTED"
    GATE_COMPLETED = "GATE_COMPLETED"
    VERIFICATION_GATE_STARTED = "VERIFICATION_GATE_STARTED"
    VERIFICATION_GATE_RECORDED = "VERIFICATION_GATE_RECORDED"
    VERIFICATION_SUITE_RECORDED = "VERIFICATION_SUITE_RECORDED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    VERIFICATION_REPAIR_SCHEDULED = "VERIFICATION_REPAIR_SCHEDULED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_INVALIDATED = "APPROVAL_INVALIDATED"
    EXECUTION_APPROVED = "EXECUTION_APPROVED"
    PROMOTION_APPROVAL_REQUESTED = "PROMOTION_APPROVAL_REQUESTED"
    PROMOTION_APPROVED = "PROMOTION_APPROVED"
    PROMOTION_APPROVAL_EXPIRED = "PROMOTION_APPROVAL_EXPIRED"
    PROMOTION_APPROVAL_INVALIDATED = "PROMOTION_APPROVAL_INVALIDATED"
    CANDIDATE_COMMIT_STARTED = "CANDIDATE_COMMIT_STARTED"
    CANDIDATE_COMMIT_RECORDED = "CANDIDATE_COMMIT_RECORDED"
    PROMOTION_DRY_RUN_RECORDED = "PROMOTION_DRY_RUN_RECORDED"
    PROMOTION_STARTED = "PROMOTION_STARTED"
    PROMOTION_COMPLETED = "PROMOTION_COMPLETED"
    PROMOTION_FAILED = "PROMOTION_FAILED"
    KNOWLEDGE_SYNC = "KNOWLEDGE_SYNC"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
    STATE_TRANSITIONED = "STATE_TRANSITIONED"
    CANCELLATION_POLICY_DECIDED = "CANCELLATION_POLICY_DECIDED"
    CANCELLATION_COMPLETED = "CANCELLATION_COMPLETED"
    CANCELLATION_BLOCKED = "CANCELLATION_BLOCKED"
    WORKTREE_CLEANUP_POLICY_DECIDED = "WORKTREE_CLEANUP_POLICY_DECIDED"
    WORKTREE_CLEANUP_COMPLETED = "WORKTREE_CLEANUP_COMPLETED"
    WORKTREE_CLEANUP_BLOCKED = "WORKTREE_CLEANUP_BLOCKED"
    ROLLBACK_REQUESTED = "ROLLBACK_REQUESTED"
    ROLLBACK_COMPLETED = "ROLLBACK_COMPLETED"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    ROLLBACK_BLOCKED = "ROLLBACK_BLOCKED"
    ROLLBACK_CODE_COMPLETED = "ROLLBACK_CODE_COMPLETED"
    ROLLBACK_EFFECTS_COMPLETED = "ROLLBACK_EFFECTS_COMPLETED"
    ROLLBACK_POLICY_DECIDED = "ROLLBACK_POLICY_DECIDED"
    ROLLBACK_HOOK_APPROVAL_REQUESTED = "ROLLBACK_HOOK_APPROVAL_REQUESTED"
    ROLLBACK_HOOK_APPROVED = "ROLLBACK_HOOK_APPROVED"
    ROLLBACK_HOOK_APPROVAL_EXPIRED = "ROLLBACK_HOOK_APPROVAL_EXPIRED"
    ROLLBACK_HOOK_APPROVAL_INVALIDATED = "ROLLBACK_HOOK_APPROVAL_INVALIDATED"
    EXECUTION_COMPENSATED = "EXECUTION_COMPENSATED"
    BUDGET_RESERVED = "BUDGET_RESERVED"
    BUDGET_COMMITTED = "BUDGET_COMMITTED"
    BUDGET_RELEASED = "BUDGET_RELEASED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"


MINIMUM_EVENT_TYPES = frozenset(
    {
        EventType.EXECUTION_CREATED,
        EventType.WORKSPACE_CREATED,
        EventType.CONTEXT_ASSEMBLED,
        EventType.CONTEXT_BLOCKED,
        EventType.PLAN_CREATED,
        EventType.NODE_STARTED,
        EventType.NODE_COMPLETED,
        EventType.NODE_FAILED,
        EventType.MODEL_REQUEST_COMPLETED,
        EventType.MODEL_REQUEST_FAILED,
        EventType.TOOL_AUTHORIZED,
        EventType.TOOL_DENIED,
        EventType.TOOL_STARTED,
        EventType.TOOL_COMPLETED,
        EventType.GATE_STARTED,
        EventType.GATE_COMPLETED,
        EventType.RETRY_SCHEDULED,
        EventType.APPROVAL_REQUESTED,
        EventType.APPROVAL_GRANTED,
        EventType.APPROVAL_REJECTED,
        EventType.APPROVAL_EXPIRED,
        EventType.PROMOTION_STARTED,
        EventType.PROMOTION_COMPLETED,
        EventType.PROMOTION_FAILED,
        EventType.KNOWLEDGE_SYNC,
        EventType.EXECUTION_COMPLETED,
        EventType.EXECUTION_FAILED,
        EventType.EXECUTION_CANCELLED,
        EventType.ROLLBACK_REQUESTED,
        EventType.ROLLBACK_COMPLETED,
        EventType.ROLLBACK_FAILED,
    }
)

CANONICAL_EVENT_TYPES = frozenset(EventType)

NODE_SCOPED_EVENT_TYPES = frozenset(
    {
        EventType.NODE_STARTED,
        EventType.NODE_COMPLETED,
        EventType.NODE_FAILED,
        EventType.MODEL_REQUEST_COMPLETED,
        EventType.MODEL_REQUEST_FAILED,
        EventType.TOOL_AUTHORIZED,
        EventType.TOOL_DENIED,
        EventType.TOOL_STARTED,
        EventType.TOOL_CALLED,
        EventType.TOOL_COMPLETED,
        EventType.TOOL_FAILED,
        EventType.BUDGET_RESERVED,
        EventType.BUDGET_COMMITTED,
        EventType.BUDGET_RELEASED,
        EventType.BUDGET_EXCEEDED,
    }
)


__all__ = [
    "CANONICAL_EVENT_TYPES",
    "MINIMUM_EVENT_TYPES",
    "NODE_SCOPED_EVENT_TYPES",
    "EventType",
]
