"""Adaptadores concretos de ferramentas (Serena, Terminal, Git)."""

from .git import GitAdapter
from .local_editing import (
    FileSnapshot,
    LocalEditingAdapter,
    LocalEditingConfigurationError,
    LocalEditingError,
    NoFileChangeError,
    PatchResult,
    PatchValidationError,
    StaleFileError,
    TextFileError,
)
from .serena import (
    SerenaAdapter,
    SerenaAdapterError,
    SerenaCapabilities,
    SerenaCapabilityError,
    SerenaConfigurationError,
    SerenaConnectionError,
    SerenaEditResult,
    SerenaMcpConfiguration,
    SerenaToolExecutionError,
    SerenaTransport,
)
from .terminal import (
    CommandCancellation,
    CommandCancelledError,
    CommandExecutionError,
    CommandRequest,
    CommandResult,
    CommandValidationError,
    EnvironmentNotAllowedError,
    ExecutableNotAllowedError,
    LegacyShellCommandError,
    TerminalAdapter,
    TerminalAdapterError,
    TerminalConfigurationError,
)

__all__ = [
    "CommandCancellation",
    "CommandCancelledError",
    "CommandExecutionError",
    "CommandRequest",
    "CommandResult",
    "CommandValidationError",
    "EnvironmentNotAllowedError",
    "ExecutableNotAllowedError",
    "FileSnapshot",
    "GitAdapter",
    "LegacyShellCommandError",
    "LocalEditingAdapter",
    "LocalEditingConfigurationError",
    "LocalEditingError",
    "NoFileChangeError",
    "PatchResult",
    "PatchValidationError",
    "SerenaAdapter",
    "SerenaAdapterError",
    "SerenaCapabilities",
    "SerenaCapabilityError",
    "SerenaConfigurationError",
    "SerenaConnectionError",
    "SerenaEditResult",
    "SerenaMcpConfiguration",
    "SerenaToolExecutionError",
    "SerenaTransport",
    "StaleFileError",
    "TerminalAdapter",
    "TerminalAdapterError",
    "TerminalConfigurationError",
    "TextFileError",
]
